Allow Skipping of Invalid Activity Functions in Struct
temporalio/sdk-go pull request #360
Opened 2021-02-11 02:45 UTC by shannontan-bolt

This allows activities to be registered that may have some Temporal activities along with other functions.

I couldn't find a way to test the negative case without causing a failure in the test start code that would require a re-run.

2021-02-13 05:44 UTC, vitarb approved these changes

2021-02-16 04:47 UTC, vitarb requested changes
Please address build failure.

2021-02-16 04:47 UTC, vitarb commented on internal/internal_worker_test.go
> +func (t *testActivityStructWithFns) InvalidActivity(ctx context.Context) { return }
This `return` should be removed, as the code won't compile this way.

2021-03-01 23:36 UTC, Sushisource commented
@shannontan-bolt I've fixed the problems and made a new PR here. I'm closing this one in favor of that. Thanks!

2021-03-01 23:36 UTC, closed without merging

2021-03-01 23:37 UTC, shannontan-bolt commented
Thanks!